# Stack file to deploy several instances of health check playground
#
# Gunicorn entrypoint: provides a nice log showing the task name,
#                      but the `/die` endpoint will not work. Why?
#
#       See README.md for details

version: "3.0"

services:
  hcp:
    image: rfenn/healthcheckplayground
    ports:
      - "10001:10000"
    entrypoint: ["/usr/local/bin/gunicorn",
                 "-w", "4",
                 "-b", ":10000",
                 "--access-logfile", "-",
                 "hcp:app"]
    entrypoint: ["python", "hcp.py"]
    tty: true
    deploy:
      replicas: 14
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
      update_config:
        parallelism: 2
        delay: 5s
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      test: ["CMD", "curl", "-sf", "http://localhost:10000/"]
